export interface TrackedCreatorSeed {
  readonly name: string;
  readonly youtube_handle: string;
  readonly subscribers: string;
  readonly focus: string;
}

export const TRACKED_CREATORS: readonly TrackedCreatorSeed[] = [
  { name: "Coin Bureau", youtube_handle: "@CoinBureau", subscribers: "2.6M", focus: "Fundamental analysis, macro, token and ecosystem research" },
  { name: "Andrei Jikh", youtube_handle: "@andreijikh", subscribers: "2.7M", focus: "Personal finance + crypto commentary, macro market views" },
  { name: "Brian Jung", youtube_handle: "@Jungernaut", subscribers: "2.1M", focus: "Crypto plus retail investing, market commentary" },
  { name: "BitBoy Crypto", youtube_handle: "@BitBoyCryptoChannel", subscribers: "1.5M", focus: "Broad altcoin coverage, narratives, news-driven calls" },
  { name: "Altcoin Daily", youtube_handle: "@AltcoinDaily", subscribers: "1.65M", focus: "Daily altcoin picks, BTC/ETH/ADA/SOL, AI tokens" },
  { name: "Alex Becker", youtube_handle: "@AlexBeckersChannel", subscribers: "1.6M", focus: "Bold altcoin calls, AI crypto (RENDER, FET, TAO)" },
  { name: "Discover Crypto", youtube_handle: "@DiscoverCrypto_", subscribers: "1.4M", focus: "SOL ecosystem, broad altcoin analysis" },
  { name: "Altcoin Buzz", youtube_handle: "@AltcoinBuzz", subscribers: "1.4M", focus: "Altcoin news, ecosystem launches, broad crypto coverage" },
  { name: "TechLead", youtube_handle: "@TechLead", subscribers: "1.4M", focus: "Crypto, tech wealth narratives, speculative commentary" },
  { name: "Benjamin Cowen", youtube_handle: "@intothecryptoverse", subscribers: "817K", focus: "Quantitative cycle analysis, BTC/ETH/ADA/DOT" },
  { name: "CryptosRUs", youtube_handle: "@CryptosRUs", subscribers: "810K", focus: "Daily BTC/ETH updates, broad alt coverage" },
  { name: "Crypto Banter", youtube_handle: "@CryptoBanterGroup", subscribers: "795K", focus: "Live trade calls, daily market analysis" },
  { name: "Sheldon Evans", youtube_handle: "@SheldonEvansX", subscribers: "700K", focus: "Altcoin picks, sustainable investing approach" },
  { name: "Crypto Casey", youtube_handle: "@CryptoCasey", subscribers: "660K", focus: "Crypto education, security, onboarding, news commentary" },
  { name: "The Moon Carl", youtube_handle: "@TheMoon", subscribers: "657K", focus: "Bold BTC price targets, TA-based calls" },
  { name: "Lark Davis", youtube_handle: "@TheCryptoLark", subscribers: "640K", focus: "Altcoin gems, SUI/NEAR, portfolio strategy" },
  { name: "Kitco News", youtube_handle: "@kitco", subscribers: "620K", focus: "Macro market news, Bitcoin and institutional crypto commentary" },
  { name: "MMCrypto", youtube_handle: "@MMCryptoTube", subscribers: "620K", focus: "Bitcoin momentum, technical analysis, leverage-style trade views" },
  { name: "EllioTrades Crypto", youtube_handle: "@elliotrades", subscribers: "560K", focus: "Altcoin narratives, growth sectors, speculative rotations" },
  { name: "DataDash", youtube_handle: "@DataDash", subscribers: "511K", focus: "Data-driven macro + crypto, LINK/DOT analysis" },
  { name: "Ivan on Tech", youtube_handle: "@IvanOnTech", subscribers: "500K", focus: "Blockchain education, ecosystem analysis, altcoin cycles" },
  { name: "InvestAnswers", youtube_handle: "@InvestAnswers", subscribers: "450K", focus: "Data-driven buy/sell calls with explicit targets" },
  { name: "Paul Barron Network", youtube_handle: "@PaulBarronNetwork", subscribers: "420K", focus: "Crypto news, token narratives, ecosystem interviews" },
  { name: "Anthony Pompliano", youtube_handle: "@AnthonyPompliano", subscribers: "420K", focus: "Bitcoin, macro, policy, institutional adoption" },
  { name: "Crypto Capital Venture", youtube_handle: "@CryptoCapitalVenture", subscribers: "402K", focus: "ADA champion, mid-cap alt predictions" },
  { name: "Austin Hilton", youtube_handle: "@AustinHilton", subscribers: "359K", focus: "Daily altcoin plays, DOGE, meme coins" },
  { name: "Bankless", youtube_handle: "@Bankless", subscribers: "310K", focus: "Ethereum, DeFi, crypto policy, on-chain investing" },
  { name: "Michael Wrubel", youtube_handle: "@MichaelWrubel", subscribers: "315K", focus: "Undervalued alts, honest quick reviews" },
  { name: "Satoshi Stacker", youtube_handle: "@StackerSatoshi", subscribers: "300K", focus: "Daily BTC + altcoin picks, AI/gaming crypto" },
  { name: "Crypto Zombie", youtube_handle: "@CryptoZombie", subscribers: "263K", focus: "Daily altcoin alerts, specific entries" },
  { name: "Crypto Jebb", youtube_handle: "@CryptoJebb", subscribers: "248K", focus: "TA chart patterns, price targets" },
  { name: "The Modern Investor", youtube_handle: "channel/UC-5HLi3buMzdxjdTdic3Aig", subscribers: "229K", focus: "Daily crypto investor updates, macro framing, risk management" },
  { name: "Raoul Pal", youtube_handle: "@RaoulGMI", subscribers: "220K", focus: "Macro cycles, institutional crypto theses, long-duration narratives" },
  { name: "CryptoBusy", youtube_handle: "@CryptoBusy", subscribers: "220K", focus: "Altcoin research, trend analysis, investor education" },
  { name: "Blockworks Macro", youtube_handle: "@BlockworksMacro", subscribers: "210K", focus: "Macro, policy, institutional crypto narratives" },
  { name: "Crypto Rover", youtube_handle: "@CryptoRover", subscribers: "210K", focus: "Daily BTC/SOL calls, altcoin analysis" },
  { name: "Wolf of All Streets", youtube_handle: "@scottmelker", subscribers: "180K", focus: "Trading, macro interviews, Bitcoin and altcoin setups" },
  { name: "Taiki Maeda", youtube_handle: "@TaikiMaeda2", subscribers: "180K", focus: "DeFi, yield rotations, ecosystem-specific opportunities" },
  { name: "VirtualBacon", youtube_handle: "@VirtualBacon", subscribers: "170K", focus: "Portfolio construction, macro + crypto allocations, risk-managed ideas" },
  { name: "Kevin Svenson", youtube_handle: "@KevinSvenson", subscribers: "140K", focus: "Bitcoin technical analysis, cycle timing, breakout setups" },
  { name: "Digital Asset News", youtube_handle: "@DigitalAssetNewsDAN", subscribers: "120K", focus: "Crypto investing commentary, risk management, portfolio views" },
  { name: "Crypto Kirby Trading", youtube_handle: "@CryptoKirbyTrading", subscribers: "120K", focus: "Technical analysis, swing trade setups, Bitcoin and majors" },
  { name: "Mikybull Crypto", youtube_handle: "@MikybullCrypto", subscribers: "110K", focus: "Bitcoin and altcoin technical analysis, swing setups" },
  { name: "Miles Deutscher", youtube_handle: "@milesdeutscher1357", subscribers: "100K", focus: "Specific entries/exits, SUI/INJ/RENDER/FET" },
  { name: "The Defiant", youtube_handle: "@TheDefiant", subscribers: "95K", focus: "DeFi news, protocol activity, on-chain ecosystem coverage" },
  { name: "ReadySetCrypto", youtube_handle: "@ReadySetCrypto", subscribers: "95K", focus: "Crypto education, portfolio strategy, market views" },
  { name: "Empire by Blockworks", youtube_handle: "@EmpireShow", subscribers: "90K", focus: "Crypto founders, infrastructure, policy and market structure" },
  { name: "Crypto Jon", youtube_handle: "@CryptoJon", subscribers: "80K", focus: "Small-cap altcoin narratives, momentum ideas" },
  { name: "Unchained", youtube_handle: "@unchainedcrypto", subscribers: "75K", focus: "Crypto policy, narratives, infrastructure, founder interviews" },
  { name: "Laura Shin", youtube_handle: "@LauraShin", subscribers: "70K", focus: "Crypto journalism, market structure, major ecosystem interviews" },
  { name: "Jacob Crypto Bury", youtube_handle: "@JacobCryptoBury", subscribers: "58K", focus: "Early small-cap gems, PENDLE/AR" },
  { name: "Johnny Harris", youtube_handle: "@johnnyharris", subscribers: "6.0M", focus: "Geopolitics and macro narratives intersecting with Bitcoin and markets" },
  { name: "99Bitcoins", youtube_handle: "@99Bitcoins", subscribers: "720K", focus: "Bitcoin and crypto education, mining, beginner-focused explainers" },
  { name: "Andreas M. Antonopoulos", youtube_handle: "@aantonop", subscribers: "TBD", focus: "EN / Global / creator education" },
  { name: "Angga Andinata", youtube_handle: "@AnggaAndinata", subscribers: "TBD", focus: "ID / Asia / creator calls" },
  { name: "BFM Crypto", youtube_handle: "channel/UC9jq6tr49rHZTUK-Jm1hV4w", subscribers: "TBD", focus: "FR / Europe / creator calls" },
  { name: "Bitcoin Expert India", youtube_handle: "@BitcoinExpertIndia", subscribers: "TBD", focus: "HI / Asia / macro bitcoin" },
  { name: "Bitcoin Indonesia", youtube_handle: "channel/UC8uYnlRXt__92AUhLWLWgFw", subscribers: "TBD", focus: "MIXED / Global / macro bitcoin" },
  { name: "Bitcoin Trading Challenge", youtube_handle: "channel/UC-dLWl8etTtPSGdbbcYffGw", subscribers: "TBD", focus: "MIXED / Global / macro bitcoin" },
  { name: "Bitinning", youtube_handle: "@Bitinning", subscribers: "TBD", focus: "HI / Asia / creator calls" },
  { name: "Blockchain Backer", youtube_handle: "channel/UCia6oYbLKo8fLOguATpACmA", subscribers: "TBD", focus: "MIXED / Global / creator calls" },
  { name: "Cilinix Crypto", youtube_handle: "channel/UC8QWLZNoN3whQ7QMwoDp78A", subscribers: "TBD", focus: "FR / Europe / creator calls" },
  { name: "Crypto Deutschland", youtube_handle: "channel/UC9M0AlqCwycSsL0XfDgaz-g", subscribers: "TBD", focus: "DE / Europe / creator calls" },
  { name: "Crypto Flash France", youtube_handle: "channel/UC7t8V-dJPWfmAXEK2tvma1A", subscribers: "TBD", focus: "FR / Europe / creator calls" },
  { name: "Crypto India I क्रिप्टो इंडिया", youtube_handle: "@cryptoindia", subscribers: "TBD", focus: "HI / Asia / creator calls" },
  { name: "Crypto Le Trone", youtube_handle: "channel/UC5kh_CumIL_usjg3pW5J9Qw", subscribers: "TBD", focus: "FR / Europe / creator calls" },
  { name: "everything hindi", youtube_handle: "@everythinghindi", subscribers: "TBD", focus: "HI / Asia / creator calls" },
  { name: "Hasheur", youtube_handle: "channel/UChlTcWDE8gd4tsl_L727NrQ", subscribers: "TBD", focus: "FR / Europe / creator calls" },
  { name: "Les Rois du Bitcoin", youtube_handle: "channel/UCv9sIj-mKR4qEr_yYAywR1A", subscribers: "TBD", focus: "FR / Europe / macro bitcoin" },
  { name: "MoneyZG", youtube_handle: "channel/UCIEvlRpHBVFthrF6pZzBEXw", subscribers: "TBD", focus: "EN / Global / creator calls" },
  { name: "PUSHPENDRA SINGH DIGITAL", youtube_handle: "@PUSHPENDRASINGHDIGITAL", subscribers: "TBD", focus: "HI / Asia / creator calls" },
  { name: "SwissCryptoJay", youtube_handle: "channel/UCWM1uBxzGpNb4RyxtFc3A8g", subscribers: "TBD", focus: "DE / Europe / creator calls" },
  { name: "Tabraiz Shams", youtube_handle: "@Tabraizshams", subscribers: "TBD", focus: "HI / Asia / creator calls" },
  { name: "The Crypto Gateway - Investire in Criptovalute", youtube_handle: "channel/UC9X2f4pVXSNzsJ2c6ZQVqBQ", subscribers: "TBD", focus: "IT / Europe / creator calls" },
  { name: "VoskCoin", youtube_handle: "channel/UCT44w6854K62cSiwA1aiXfw", subscribers: "TBD", focus: "EN / Global / creator calls" },
  { name: "Wael - Blockchain Academics", youtube_handle: "channel/UChdlb_HfMQ3gtzo7_K22RLA", subscribers: "TBD", focus: "MIXED / Global / creator calls" },
  { name: "Amila Bro", youtube_handle: "@AmilaBro", subscribers: "TBD", focus: "SI / Asia / creator calls" },
  { name: "Bitcoin TV", youtube_handle: "channel/UCSSXEml-1o9J1ZsNGMF1lQg", subscribers: "TBD", focus: "MIXED / Global / macro bitcoin" },
  { name: "Blockchain Ben", youtube_handle: "channel/UC3p4k68KnVGJvLQkEE83P_w", subscribers: "TBD", focus: "MIXED / Global / creator calls" },
  { name: "Blockchain Crypto", youtube_handle: "channel/UCyyqk56AXPMOz40-Pu7Zo-g", subscribers: "TBD", focus: "MIXED / Europe / creator calls" },
  { name: "Brandon Kelly Crypto Trader", youtube_handle: "channel/UC-f5nPBEDyUBZz_jOPBwAfQ", subscribers: "TBD", focus: "MIXED / Global / creator calls" },
  { name: "Christian Victorius", youtube_handle: "@ChristianVictorius", subscribers: "TBD", focus: "ID / Asia / creator calls" },
  { name: "CoinCasso", youtube_handle: "channel/UCRGIWPbcK7pPlZ0bePHZxDQ", subscribers: "TBD", focus: "MIXED / Global / creator calls" },
  { name: "CoinsKid", youtube_handle: "channel/UCeBbEvlSOeJMwSVYOdXOvvw", subscribers: "TBD", focus: "EN / Global / creator calls" },
  { name: "Crypto Basics", youtube_handle: "@CryptoBasicsBD", subscribers: "TBD", focus: "BN / Asia / creator calls" },
  { name: "Crypto Kaiba", youtube_handle: "channel/UCx9Z8LQWzCehWv5GqqPUPjw", subscribers: "TBD", focus: "MIXED / Europe / creator calls" },
  { name: "Crypto Love", youtube_handle: "channel/UCu7Sre5A1NMV8J3s2FhluCw", subscribers: "TBD", focus: "EN / Global / creator calls" },
  { name: "Crypto Profi Schweiz", youtube_handle: "channel/UCwi9Ntnk_sCw0DSW8bP0DPg", subscribers: "TBD", focus: "DE / Europe / creator calls" },
  { name: "Crypto Shubhrant chaudhary", youtube_handle: "@cryptoshubhrantchaudhary8012", subscribers: "TBD", focus: "HI / Asia / creator calls" },
  { name: "CryptoJack", youtube_handle: "channel/UCBjrrP9frGRuRwoAJ4RQdag", subscribers: "TBD", focus: "EN / Global / creator calls" },
  { name: "Czero : Crypto et Bitcoin pour tous", youtube_handle: "channel/UCKffaugnQVKp3G0hrhP-tew", subscribers: "TBD", focus: "FR / Europe / macro bitcoin" },
  { name: "Didi Random", youtube_handle: "channel/UCoMc0zniPatlGpR6OQiM-Qg", subscribers: "TBD", focus: "DE / Europe / creator calls" },
  { name: "Earn With Rk", youtube_handle: "@EarnWithRK", subscribers: "TBD", focus: "HI / Asia / creator calls" },
  { name: "Earn With Sapna", youtube_handle: "@earnwithsapna", subscribers: "TBD", focus: "HI / Asia / creator calls" },
  { name: "EZC - Trading", youtube_handle: "channel/UCaEmEcGngLdmOTeyirL4j6w", subscribers: "TBD", focus: "FR / Europe / creator calls" },
  { name: "Jesse Eckel", youtube_handle: "channel/UCPFMk8WxX3SJKy1jh61xxGw", subscribers: "TBD", focus: "EN / Global / creator calls" },
  { name: "Joe Parys Crypto", youtube_handle: "channel/UCRukJuuBAdoHMTBIsFJAgvw", subscribers: "TBD", focus: "EN / Global / creator calls" },
  { name: "JRNY Crypto", youtube_handle: "channel/UC188KLMYLLGqVJZdYq7mYFw", subscribers: "TBD", focus: "EN / Global / creator calls" },
  { name: "KryptoJugend", youtube_handle: "channel/UCRMF41Ybk3qVIyo0fuG8P0g", subscribers: "TBD", focus: "DE / Europe / creator calls" },
  { name: "PARLONS DE TOUT", youtube_handle: "channel/UC_PZx3xmmWTtXzB_fc0pz9w", subscribers: "TBD", focus: "FR / Europe / creator calls" },
  { name: "Real-Crypto", youtube_handle: "channel/UC93MJYEjwCW3-9ipq09k7XQ", subscribers: "TBD", focus: "MIXED / Global / creator calls" },
  { name: "Augusto Backes", youtube_handle: "@AugustoBackes", subscribers: "TBD", focus: "PT / Latin America / creator calls" },
  { name: "Aventure Crypto", youtube_handle: "channel/UCdeNXmhpAIHMAGQD3vFW99Q", subscribers: "TBD", focus: "FR / Europe / creator calls" },
  { name: "Bintense", youtube_handle: "channel/UClPeiwRWRPf6XLMLRYFsdaw", subscribers: "TBD", focus: "MIXED / Europe / creator calls" },
  { name: "BitJom PH", youtube_handle: "@BitJomPH", subscribers: "TBD", focus: "FIL / Asia / creator calls" },
  { name: "Crypto Alina", youtube_handle: "channel/UCrXpxOgkXOAJnEdbGVnF1gg", subscribers: "TBD", focus: "MIXED / Europe / creator calls" },
  { name: "Crypto Banter +", youtube_handle: "channel/UCybasP-2D2b5kTLAb_kvhWQ", subscribers: "TBD", focus: "EN / Global / creator calls" },
  { name: "Crypto Crow", youtube_handle: "channel/UCwsRWmIL5XKqFtdytBfeX0g", subscribers: "TBD", focus: "EN / Global / creator calls" },
  { name: "Crypto Face", youtube_handle: "channel/UCnpL_SpKLZpwAAIWmWpCIzQ", subscribers: "TBD", focus: "EN / Global / creator calls" },
  { name: "Crypto Inspector", youtube_handle: "channel/UCEpMrACLAX8W2NvbWe_kZQQ", subscribers: "TBD", focus: "MIXED / Europe / creator calls" },
  { name: "Crypto Mason", youtube_handle: "channel/UCPR9ga3sv5oakMB544M61Bw", subscribers: "TBD", focus: "EN / Global / creator calls" },
  { name: "Crypto Sheinix", youtube_handle: "@CryptoSheinix", subscribers: "TBD", focus: "ES / Europe / creator calls" },
  { name: "Docteur Crypto", youtube_handle: "channel/UC35L0fCIFfpgTne_3-JnFIg", subscribers: "TBD", focus: "FR / Europe / creator calls" },
  { name: "Dương Alex", youtube_handle: "@duongalex2", subscribers: "TBD", focus: "VI / Asia / creator calls" },
  { name: "Ismail Luno", youtube_handle: "@IsmailLuno", subscribers: "TBD", focus: "MS / Asia / creator calls" },
  { name: "Joris", youtube_handle: "channel/UCzdIts_jgMM-ehV4bKmObKw", subscribers: "TBD", focus: "MIXED / Europe / creator calls" },
  { name: "Kenal Kripto", youtube_handle: "@KenalKripto", subscribers: "TBD", focus: "ID / Asia / creator calls" },
  { name: "KRYPTOSPHERE®", youtube_handle: "channel/UCXkbPLYTAegwnqeMMC08YzA", subscribers: "TBD", focus: "FR / Europe / creator calls" },
  { name: "Not Your Financial Advisor", youtube_handle: "@CryptopherTan", subscribers: "TBD", focus: "MIXED / Asia / creator calls" },
  { name: "Simply Bitcoin", youtube_handle: "@SimplyBitcoin", subscribers: "TBD", focus: "EN / North America / macro bitcoin" },
  { name: "The Bitcoin Express", youtube_handle: "channel/UCEjgpiDPhTErrJm6zeNeAAw", subscribers: "TBD", focus: "EN / Global / macro bitcoin" },
  { name: "Thinking Crypto", youtube_handle: "channel/UCjpkwsuHgYx9fBE0ojsJ_-w", subscribers: "TBD", focus: "EN / Global / creator calls" },
  { name: "Tom Crown", youtube_handle: "channel/UCiuD3eNaZ95eSXImp_eSIww", subscribers: "TBD", focus: "EN / Global / creator calls" },
] as const;

export const TRACKED_CREATOR_COUNT = TRACKED_CREATORS.length;
