import { NextRequest, NextResponse } from "next/server";
import { recordAlertUnsubscribe } from "@/lib/alerts";
import { verifyUnsubscribeToken } from "@/lib/unsubscribe-token";

export const dynamic = "force-dynamic";

function badRequest(message: string): NextResponse {
  return NextResponse.json(
    { error: message },
    { status: 400, headers: { "cache-control": "no-store" } },
  );
}

/**
 * GET /api/alerts/unsubscribe?token=<signed-token>
 *
 * Verifies the HMAC signature on the token and, if valid, acknowledges
 * the unsubscribe. The token is generated by @/lib/unsubscribe-token
 * when building digest emails.
 *
 * Persists the opt-out before acknowledging success so future alert
 * dispatches exclude this user and watchlist rows are removed.
 */
export async function GET(request: NextRequest): Promise<NextResponse> {
  const url = new URL(request.url);
  const token = url.searchParams.get("token");
  if (!token) return badRequest("missing_token");

  const payload = verifyUnsubscribeToken(token);
  if (!payload) return badRequest("invalid_token");

  await recordAlertUnsubscribe(payload.userId);

  return NextResponse.json(
    {
      success: true,
      message:
        "Unsubscribe received. Per-creator alerts for your account will stop at the next dispatch. You can re-enable alerts any time from your watchlist.",
      user_id: payload.userId,
    },
    { status: 200, headers: { "cache-control": "no-store" } },
  );
}
